name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: test time
      env:
        ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      run: |
         $env:USERNAME
         Write-Host "downloading ZeroTier msi progra..."
         $installerPath = "$env:TEMP\ZeroTierInstaller.msi"
         Invoke-WebRequest -Uri "https://download.zerotier.com/dist/ZeroTier%20One.msi" -OutFile $installerPath
         Write-Host "install working ZeroTier..."
         Start-Process -FilePath "msiexec.exe" -ArgumentList "/i $installerPath /qn /norestart" -Wait
         cd 'C:\Program Files\'
         ls
         cd 'C:\Program Files (x86)\'
         ls
         # Start-Sleep -Seconds 5
         # zerotier-cli join "$ZEROTIER_ID"
         # Start-Sleep -Seconds 5
         # zerotier-cli info
         # $currentUsername = $env:USERNAME
         # Set-LocalUser -Name $currentUsername -Password 123456
         
