name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: test time
      env:
        ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      run: |
         # $env:USERNAME
         # Write-Host "downloading ZeroTier msi progra..."
         # $installerPath = "$env:TEMP\ZeroTierInstaller.msi"
         # Invoke-WebRequest -Uri "https://download.zerotier.com/dist/ZeroTier%20One.msi" -OutFile $installerPath
         # Write-Host "install working ZeroTier..."
         # Start-Process -FilePath "msiexec.exe" -ArgumentList "/i $installerPath /qn /norestart" -Wait
         # cd 'C:\Program Files\'
         # ls
         # cd 'C:\Program Files (x86)\ZeroTier\One\'
         # ls
         # ./zerotier_desktop_ui.exe
         # Start-Sleep -Seconds 60
         # ./zerotier-cli join "1d71939404d367e6"
         # Start-Sleep -Seconds 5
         # ./zerotier-cli info
         # Start-Sleep -Seconds 5
         # ./zerotier-cli info
         # ipconfig
         Set-LocalUser -Name 'runneradmin' -Password 'a1'
         # Start-Sleep -Seconds 3600
