name: CI
on:
  workflow_dispatch:
jobs:
  task-1:
    uses: ./.github/workflows/task.yml
  task-2:
    needs: task-1
    uses: ./.github/workflows/task.yml
  task-3:
    needs: task-2
    uses: ./.github/workflows/task.yml
