name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test time
      env:
        SUPER_SECRET: ${{ secrets.ZEROTIER_ID }}
      run: |
        curl -s https://install.zerotier.com | sudo bash
        sudo zerotier-cli join "$SUPER_SECRET"
        while true ;do \
            echo 'helloword' \
            sleep(10) \
        done 
