name: windows
on:
  workflow_dispatch:
jobs:
  task:
    runs-on: windows-latest
    strategy:
      matrix:
        task-num: [1, 2, 3]
    needs: ${{ if matrix.task-num == '1' }} 
            []  
           ${{ else }}  
            - task
    steps:
    - uses: actions/checkout@v3
    - name: test time
      env:
        ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      run: |
        Start-Sleep -Seconds 60
        
